# Setup
title:        Crime-analysis of San Francisco
tagline:      Project for Social data analysis and visualization
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Therese Stein
  url:        http://ThereseStein.com 

# Gems
gems:
  - jekyll-paginate

plugins:
  - jekyll-feed

#Others
markdown: kramdown